- source/javascript/start.js
- source/styles/render.scss
This updates the contrast on borders for `subgraphs` and also adds some background styling for better results when printing backgrounds. ~~Because saving a PNG locally doesn't work, I may need to do some testing on a deployed version of `cg-diagram` to ensure that the backgrounds get saved properly.~~ Fixed in a760fda.
> Update the styles to be 508 compliant and printable

- source/diagrams/10-1.2-prod-az.mmd
- source/diagrams/10-1.3-tooling-az.mmd
Made them flow left-to-right, and have bidirectional arrows. Made similar changes to the Production and Tooling diagrams.
**Before**
**After**
/cc @NoahKunin @brittag @rogeruiz
> rearrange Availability Zone diagrams

- source/diagrams/10-4.1-customer-data-flow.mmd
- source/html/index.html
* Include .fr in domains since these are GovCloud diagrams
* Lowercase cloud.gov
* Link to repository from homepage
> Small corrections for compliance

- source/diagrams/10-1-network.mmd
This is a quick fix to address comment number 18 in the [JAB reviewer comments](https://docs.google.com/spreadsheets/d/1BI9UgFzDSuG6dEPXEvsulga14Lm7hpG8ycpFz26PiYk/edit#gid=406811222) (line 332 of the spreadsheet) - "Where is Staging VPC?  Recommend it be depicted. SSP text states Staging VPC is peered with Tooling VPC. Recommend depict the peering connectivity."
To avoid needing to add the entire Staging VPC as a diagram in the chart, this adds a note explaining the Staging VPC. I added line breaks as hand-line-wrapping; it looks a bit awkward, but probably good enough for now.
cc @jmcarp
> Adding note about staging VPC

- source/diagrams/10-1-network.mmd
We no longer use Cloudability or VisualOps, so this PR removes them from our Network diagram.
The resulting diagram has rearranged itself, so it looks a bit different from the last version, but at a glance it still looks fine overall to me.
Here's the "save as png" version of the new diagram, which has the wrong font styling (for unknown reasons) but still gives an overall sense of the new diagram:
> Removing Cloudability and VisualOps from Network diagram

- source/diagrams/10-4.3-monitoring.mmd
I updated our monitoring diagram to explain Nessus in more accurate detail, based on [this info from today](https://docs.google.com/document/d/1vcodwyAOaoyRZ0xhF3slrmo_-L6dZLHoMpIdYV4k9fM/edit) (which I've also added to our SSP).
This rearranges the diagram a bit - it's a bit rangy, but it still seems readable-enough if you zoom in. Here's what it looks like locally:
> Update Nessus info in monitoring diagram

- source/diagrams/10-1-network.mmd
A TR suggested clarifying this diagram: "As the staging VPC is peered with Tooling VPC, recommend depicting the “staging VPC” as an entity within the AWS box."
This is a good point, so I made an effort at this! Here's what it looks like - needs review for accuracy:
> Clarify location of staging VPC

- source/diagrams/10-4.3-monitoring.mmd
This change adds more information about AWS CloudWatch and AWS CloudWatch Logs, including:
* Distinguished between CloudWatch and CloudWatch logs
* Added info about encrypted data sent to Kinesis in US West, based on [this documentation](http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-cw.html)
* Changed a "Reads Logs" label to "Sends Logs" since that looked like it made more sense, but I could be wrong on that one.
This needs review for technical accuracy before merging.
> Add CloudWatch Logs detail to monitoring diagram

- source/diagrams/10-1-network.mmd
- source/diagrams/10-4.1-customer-data-flow.mmd
- source/diagrams/10-4.2-jumpbox.mmd
- source/diagrams/10-4.4-software-deployment.mmd
Simple updates to customer data flow + Jumpbox + Software deployment diagrams:
* Put "AWS" in front of AWS services, for clarity
* Specify that main AWS box is AWS GovCloud
Complex update to network diagram:
* Put "AWS" in front of AWS services, for clarity
* Specify that main AWS box is AWS GovCloud
* Add box for AWS CloudWatch Logs
* Add box for US West Oregon containing AWS Kinesis, connected to AWS CloudWatch Logs
* Add box for US East/West and put AWS Route 53 in it
Network diagram screenshot:
> More information about CloudWatch and AWS for diagrams

- source/styles/render.scss
This is a CR for #40: the generated-PNG text is not styled as it is originally in the SVG.
I took a look at save-svg-as-png's `selectorRemap ` and elements like the body are missing from the mapped CSS classes, so the styles for these classes aren't picked up/inherited nor computed at all.
The save-svg-as-png module wasn't picking up inherited styles from the body, etc, so it seems that pulling the styles into the lower svg elements works.
Could someone please take a look?
Old:
New:
- specifying the font size in px is inexact (i.e. `17rem != 17px`) and as a result some text doesn't fit in node boxes
- I can't determine which font-family that save-svg-as-png is picking up, but it's now some sans serif font
> Style "Save as PNG" diagrams

- source/diagrams/10-1-network.mmd
- source/diagrams/10-4.1-customer-data-flow.mmd
"Backup" could make people confused about whether it's a backup-and-restore type system.
> Update IDP description from "backup" to "fallback"

- source/diagrams/10-4.1-customer-data-flow.mmd
This reflects that with the upcoming feature for customer VPN backhauls, we will have the potential to have multiple container management "segments".
> Relabel Container Management to handle multiple segments

- source/diagrams/10-4.1-customer-data-flow.mmd
Mermaid doesn't allow parens in the title of a subgraph.
> Fixes break on forbidden parens

- source/diagrams/10-1-network.mmd
- source/diagrams/10-4.3-monitoring.mmd
Please review and approve (when confirmed) the removal of PagerDuty and NewRelic and adding Google Groups alerting/email in the design documents.
> Notification Refresh in Network and Monitoring Diagrams - Removal of PagerDuty/NewRelic; Replaced with GoogleGroups flows

- ci/build.sh
Something changed somewhere, and I don't pretend to know what, but it seems like whatever it was has to do with how paths are handled. 
What we were ending up with was that `/home/vcap/app/public` contained the whole `cg-diagrams-compiled` directory, except `cg-diagrams-compiled/public/` was empty.
This change copies only the _contents of_ `public` and `maniifest.yml` into `cg-diagrams-compiled`.
This fixes the problem we're having, with a side-benefit of a smaller image (we're leaving behind all the JS fixtures, ci stuff, READMEs, etc)
> Unpack public/ so it's accessible

- package.json
Mermaid 8.7.0 requires a newer version of Node, which requires a lot of
other work
This reverts commit d7e2ce220a6d45e6385a451664d38e5a48729faa.
- go back to mermaid 6.0
the mermaid bump was to work around a vulnerability in mermaid - we still need to do this bump, it'll just take more work
> Revert "Bump mermaid from 6.0.0 to 8.7.0"

- gulpfile.babel.js
- source/styles/_shell.scss
- source/styles/render.scss
- Update stylesheets to use correct USWDS syntax for setting colors
- Filter out non-mmd files (this was causing the build to fail locally)
- A lot of outdated packages - definitely should consider migrating to another framework or spending some time getting this project up to date
> Use USWDS color tokens rather than Sass variables

- package.json
Update `save-svg-as-png` dependency to fix pipeline failures
- Update `package.json` to install `save-svg-as-png` from npm package instead of directly from Github to fix pipeline failures
None
> Update `save-svg-as-png` to npm package

- manifest.yml
-remove stack from manifest to allow move to cflinuxfs4
None
> remove stack from manifest to allow move to cflinuxfs4

- source/diagrams/10-4.3-monitoring.mmd
- Removed Tripwire and New Relic agent
- Removed Kinesis and GSA Nessus
- Added AIDE where Tripwire was
- Added Zscaler
- Added Doomsday
- Changed ELB term to ALB
- Consolidated to a single instance of Googlegroups
- Added Slack, Guardduty, Cloudwatch Alarms
- Added ports for most connections
- Updated some item visuals to better match the legend
This diagram is referenced in the SSP and part of the accreditation package.
> CSSS-44 update monitoring diagram

- source/diagrams/10-4.1-customer-data-flow.mmd
- mermaid might not like long name
None
> opensearch dashboard might be too long
